### PR TITLE
Proceed to next step nudge

### LINKED ISSUE #1102: Next button should highlight when all tasks on a stage are complete
Currently on the form based interfaces, we show a horizontal progress bar to indicate progress through the stage. This doesn't quite work for a number of reasons:

- It is visually jarring next to the vertical progress bar
- It doesnt actually show progress, because it doesn't take into account validation

We should instead have the "next" button enter a visual state that indicates the participant can/should move forwards.

### PR DESCRIPTION
**Pull request by wwqrd**
Updates form and slide forms to set global ready state when the form isValid, and has been scrolled to 100%. This ready state sets a pulse nudge highlight for the protocol navigation "next button".

- Removes the horizontal progress bar from ego forms, and replaces it with a notice to scroll
  - notice to scroll will hide when the user starts scrolling, and reappear after 5s if the user still hasn't reached the end of the screen, if they scroll again it will hide again, repeat.
- Updates the horizontal progress bar on slide forms to no longer show a nudge animation.

Resolves #1102
Potentially #1040

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
What is the notice to scroll?

If you invalidate the form *after* scrolling to the bottom of the form, the next button will sometimes continue to pulse even though the form isn't valid anymore. For example, on the development protocol, on the ego form, fill out the whole form, scroll up a little, and then scroll to the bottom. Then clear the date of birth, which invalidates the form. The pulse stays. Order of events seems to matter, because filling out the date of birth after scrolling to the bottom activates the pulse, and then clearing it deactivates the pulse like I'd expect.

**Comment by wwqrd** [comment]
> What is the notice to scroll?

scroll to see more

This is here in case there are questions below the fold.

**Comment by rebeccamadsen** [comment]
I get this when trying to click on the timeline or menu->stages.

image

```
Uncaught TypeError: scrollerRef.current.scrollTo is not a function
    at scrollToLocation (:3000/static/js/bundle.js:372991)
    at :3000/static/js/bundle.js:373036
    at commitHookEffectListMount (:3000/static/js/bundle.js:274472)
    at commitLifeCycles (:3000/static/js/bundle.js:274528)
    at commitLayoutEffects (:3000/static/js/bundle.js:277544)
    at HTMLUnknownElement.callCallback (:3000/static/js/bundle.js:254929)
    at Object.invokeGuardedCallbackDev (:3000/static/js/bundle.js:254978)
    at invokeGuardedCallback (:3000/static/js/bundle.js:255033)
    at commitRootImpl (:3000/static/js/bundle.js:277282)
    at unstable_runWithPriority (:3000/static/js/bundle.js:323983)
    at runWithPriority$1 (:3000/static/js/bundle.js:265780)
    at commitRoot (:3000/static/js/bundle.js:277122)
    at finishSyncRender (:3000/static/js/bundle.js:276548)
    at performSyncWorkOnRoot (:3000/static/js/bundle.js:276534)
    at :3000/static/js/bundle.js:265830
    at unstable_runWithPriority (:3000/static/js/bundle.js:323983)
    at runWithPriority$1 (:3000/static/js/bundle.js:265780)
    at flushSyncCallbackQueueImpl (:3000/static/js/bundle.js:265825)
    at flushSyncCallbackQueue (:3000/static/js/bundle.js:265813)
    at scheduleUpdateOnFiber (:3000/static/js/bundle.js:275940)
    at Object.enqueueForceUpdate (:3000/static/js/bundle.js:267419)
    at AnimateSharedLayout../node_modules/react/cjs/react.development.js.Component.forceUpdate (:3000/static/js/bundle.js:300239)
    at AnimateSharedLayout../node_modules/framer-motion/dist/framer-motion.es.js.AnimateSharedLayout.scheduleUpdate (:3000/static/js/bundle.js:159708)
    at forceUpdate (:3000/static/js/bundle.js:159610)
    at onExit (:3000/static/js/bundle.js:159319)
    at onExitComplete (:3000/static/js/bundle.js:159140)
    at safeToRemove (:3000/static/js/bundle.js:157029)
```

I see the scroll notice now. Is it just on the ego form? I didn't notice it on the Alter form or Alter edge form, perhaps because those have scrollbars? This seems to work generally well, although I can get it in a funky state that it only disappears for a second before coming back if I scroll little by little.

**Comment by wwqrd** [comment]
Sorry I should have caveated - did you run an npm install? the UI package needs to be updated for scrollTo to work.

**Comment by wwqrd** [comment]
I've fixed the scroll prompt, and increased the delay to 7 seconds. You're correct that it isn't on the alter forms, do you think it should be?

**Comment by rebeccamadsen** [comment]
> Sorry I should have caveated - did you run an npm install? the UI package needs to be updated for scrollTo to work.

I did an install, but needed to delete the UI package from node_modules to get it to install the correct version. It works now!

> I've fixed the scroll prompt, and increased the delay to 7 seconds. You're correct that it isn't on the alter forms, do you think it should be?

This fix works great! I'm not sure if it's needed on alter forms, since they are in their own panel.

**Review by rebeccamadsen — APPROVED** [review]
This looks good to me!

**Pull request merged**
